// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szsypwfabhiehbwvjwbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6c3lwd2ZhYmhpZWhid3Zqd2JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNjM4ODMsImV4cCI6MjA1ODkzOTg4M30.xNwQZaJ4-dG_uY1Oe2Ft5j3AYQTLT7K5Xclc_6AyE44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);